export interface QAItem {
  id: string
  question: string
  answer: string
  category: string
  difficulty: "easy" | "medium" | "hard"
  tags: string[]
  code?: string
}

export const qaContent: QAItem[] = [
  // Basic SQL
  {
    id: "qa-basic-01",
    category: "basic-sql",
    difficulty: "easy",
    question: "How do I select all columns from a table?",
    answer: "Use SELECT * to retrieve all columns from a table. While convenient for exploration, it's better to specify columns explicitly in production code for clarity and performance.",
    tags: ["SELECT", "basics"],
    code: "-- Select all columns\nSELECT * FROM employees;\n\n-- Better: specify columns explicitly\nSELECT id, name, department, salary FROM employees;",
  },
  {
    id: "qa-basic-02",
    category: "basic-sql",
    difficulty: "easy",
    question: "How do I filter rows with WHERE?",
    answer: "The WHERE clause filters rows based on conditions. You can use comparison operators (=, <, >, <=, >=, !=), logical operators (AND, OR, NOT), and pattern matching (LIKE, IN, BETWEEN).",
    tags: ["WHERE", "filtering"],
    code: "-- Simple comparison\nSELECT * FROM employees WHERE department = 'Engineering';\n\n-- Multiple conditions\nSELECT * FROM orders WHERE total > 100 AND status = 'pending';\n\n-- Range filter\nSELECT * FROM transactions WHERE amount BETWEEN 50 AND 200;\n\n-- Pattern matching\nSELECT * FROM customers WHERE email LIKE '%@example.com';",
  },
  {
    id: "qa-basic-03",
    category: "basic-sql",
    difficulty: "easy",
    question: "How do I sort query results?",
    answer: "Use ORDER BY to sort results. ASC (default) for ascending, DESC for descending. You can sort by multiple columns.",
    tags: ["ORDER BY", "sorting"],
    code: "-- Ascending (default)\nSELECT name, salary FROM employees ORDER BY salary;\n\n-- Descending\nSELECT name, salary FROM employees ORDER BY salary DESC;\n\n-- Multiple columns\nSELECT department, name, salary FROM employees\nORDER BY department ASC, salary DESC;",
  },
  {
    id: "qa-basic-04",
    category: "basic-sql",
    difficulty: "easy",
    question: "How do I limit the number of results?",
    answer: "Use LIMIT to restrict the number of rows returned. Combine with OFFSET for pagination. SQLite uses LIMIT/OFFSET syntax.",
    tags: ["LIMIT", "pagination"],
    code: "-- Top 5 highest paid\nSELECT name, salary FROM employees\nORDER BY salary DESC\nLIMIT 5;\n\n-- Pagination (rows 11-20)\nSELECT * FROM employees\nORDER BY id\nLIMIT 10 OFFSET 10;",
  },
  // JOINs
  {
    id: "qa-join-01",
    category: "joins",
    difficulty: "easy",
    question: "What's the difference between INNER JOIN and LEFT JOIN?",
    answer: "INNER JOIN returns only rows that have matching values in both tables. LEFT JOIN returns all rows from the left table and matching rows from the right (with NULLs where no match exists). Use INNER JOIN when you only need matched records; use LEFT JOIN when you need all records from the primary table.",
    tags: ["JOIN", "INNER JOIN", "LEFT JOIN"],
    code: "-- INNER JOIN: only customers with orders\nSELECT c.name, o.order_id, o.total\nFROM customers c\nINNER JOIN orders o ON c.customer_id = o.customer_id;\n\n-- LEFT JOIN: all customers, even without orders\nSELECT c.name, o.order_id, o.total\nFROM customers c\nLEFT JOIN orders o ON c.customer_id = o.customer_id;",
  },
  {
    id: "qa-join-02",
    category: "joins",
    difficulty: "medium",
    question: "How do I join more than two tables?",
    answer: "Chain multiple JOIN clauses. Each JOIN should have its own ON condition. The order of joins matters for performance — join the smallest filtered result sets first.",
    tags: ["JOIN", "multi-table"],
    code: "-- Three-table join\nSELECT c.name, o.order_id, p.name as product, o.quantity\nFROM customers c\nJOIN orders o ON c.customer_id = o.customer_id\nJOIN products p ON o.product_id = p.product_id\nWHERE o.status = 'delivered';",
  },
  {
    id: "qa-join-03",
    category: "joins",
    difficulty: "medium",
    question: "What is a SELF JOIN and when would I use it?",
    answer: "A SELF JOIN joins a table to itself. Common uses include finding hierarchical relationships (employees and managers), comparing rows within the same table, and finding duplicates.",
    tags: ["SELF JOIN", "hierarchical"],
    code: "-- Find employees and their managers\nSELECT e.name as employee, m.name as manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.id;",
  },
  {
    id: "qa-join-04",
    category: "joins",
    difficulty: "easy",
    question: "How do I find records that don't have matches in another table?",
    answer: "Use a LEFT JOIN with a NULL check on the right table's primary key, or use NOT EXISTS / NOT IN with a subquery. The LEFT JOIN approach is often more efficient.",
    tags: ["anti-join", "LEFT JOIN"],
    code: "-- Customers without orders (anti-join)\nSELECT c.name, c.email\nFROM customers c\nLEFT JOIN orders o ON c.customer_id = o.customer_id\nWHERE o.order_id IS NULL;\n\n-- Alternative with NOT EXISTS\nSELECT c.name, c.email\nFROM customers c\nWHERE NOT EXISTS (\n  SELECT 1 FROM orders o WHERE o.customer_id = c.customer_id\n);",
  },
  {
    id: "qa-join-05",
    category: "joins",
    difficulty: "medium",
    question: "What's a CROSS JOIN and when is it useful?",
    answer: "A CROSS JOIN produces the Cartesian product of two tables — every row from table A paired with every row from table B. It's useful for generating combinations (e.g., all products × all stores) or creating test data.",
    tags: ["CROSS JOIN", "cartesian"],
    code: "-- Generate all department × month combinations\nSELECT DISTINCT e.department, '2024-01' as month\nFROM employees e\nCROSS JOIN (SELECT 1) t\nUNION\nSELECT DISTINCT e.department, '2024-02' as month\nFROM employees e;",
  },
  // Aggregation
  {
    id: "qa-agg-01",
    category: "aggregation",
    difficulty: "easy",
    question: "How do I count rows and compute averages?",
    answer: "Use aggregate functions: COUNT(), AVG(), SUM(), MIN(), MAX(). They operate on a group of rows and return a single value. Combine with GROUP BY to get per-group results.",
    tags: ["COUNT", "AVG", "SUM", "aggregation"],
    code: "-- Basic aggregates\nSELECT COUNT(*) as total_employees,\n       AVG(salary) as avg_salary,\n       SUM(salary) as total_payroll\nFROM employees;\n\n-- Per department\nSELECT department,\n       COUNT(*) as emp_count,\n       ROUND(AVG(salary), 0) as avg_salary\nFROM employees\nGROUP BY department;",
  },
  {
    id: "qa-agg-02",
    category: "aggregation",
    difficulty: "medium",
    question: "How do I filter groups with HAVING?",
    answer: "HAVING filters groups after aggregation (unlike WHERE which filters rows before aggregation). Use HAVING with aggregate conditions like COUNT(*) > 5 or AVG(salary) > 80000.",
    tags: ["HAVING", "filter groups"],
    code: "-- Departments with high average salary\nSELECT department,\n       COUNT(*) as emp_count,\n       ROUND(AVG(salary), 0) as avg_salary\nFROM employees\nGROUP BY department\nHAVING AVG(salary) > 70000\nORDER BY avg_salary DESC;",
  },
  {
    id: "qa-agg-03",
    category: "aggregation",
    difficulty: "medium",
    question: "How do I use GROUP BY with multiple columns?",
    answer: "Grouping by multiple columns creates subgroups. For example, grouping by department AND job title gives you counts for each unique combination. The order of columns in GROUP BY affects how result sets are sorted.",
    tags: ["GROUP BY", "multi-column"],
    code: "-- Sales by category and status\nSELECT category,\n       status,\n       COUNT(*) as tx_count,\n       ROUND(SUM(amount), 2) as total_amount\nFROM transactions\nGROUP BY category, status\nORDER BY category, status;",
  },
  // Subqueries
  {
    id: "qa-sub-01",
    category: "subqueries",
    difficulty: "medium",
    question: "What's the difference between correlated and non-correlated subqueries?",
    answer: "A non-correlated subquery runs independently and once. A correlated subquery references columns from the outer query and runs once per row. Non-correlated subqueries are generally faster. Correlated subqueries are useful for row-by-row comparisons.",
    tags: ["subquery", "correlated"],
    code: "-- Non-correlated: highest salary overall\nSELECT name, salary FROM employees\nWHERE salary = (SELECT MAX(salary) FROM employees);\n\n-- Correlated: employees earning above dept average\nSELECT e.name, e.department, e.salary\nFROM employees e\nWHERE e.salary > (\n  SELECT AVG(salary) FROM employees\n  WHERE department = e.department\n);",
  },
  {
    id: "qa-sub-02",
    category: "subqueries",
    difficulty: "medium",
    question: "How do I use IN, ANY, and ALL with subqueries?",
    answer: "IN checks if a value matches any in a list. ANY compares a value to any single value returned by the subquery. ALL compares against every value. Use these for multi-row subquery comparisons.",
    tags: ["IN", "ANY", "ALL", "subquery"],
    code: "-- IN: employees in specific departments\nSELECT name, salary FROM employees\nWHERE department IN (\n  SELECT department FROM employees\n  GROUP BY department\n  HAVING AVG(salary) > 80000\n);\n\n-- ANY: products cheaper than any 'Electronics' item\nSELECT name, price FROM products\nWHERE price < ANY (\n  SELECT price FROM products WHERE category = 'Electronics'\n);",
  },
  // Window Functions
  {
    id: "qa-win-01",
    category: "window-functions",
    difficulty: "hard",
    question: "How do I use ROW_NUMBER() to rank rows?",
    answer: "ROW_NUMBER() assigns a unique sequential number to each row within a partition. Use ORDER BY inside the OVER clause to control the numbering. Combine with PARTITION BY to reset the count per group.",
    tags: ["ROW_NUMBER", "ranking", "window function"],
    code: "-- Rank employees by salary within each department\nSELECT name, department, salary,\n       ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) as dept_rank\nFROM employees;\n\n-- Top 2 per department\nSELECT * FROM (\n  SELECT name, department, salary,\n         ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) as rn\n  FROM employees\n) WHERE rn <= 2;",
  },
  {
    id: "qa-win-02",
    category: "window-functions",
    difficulty: "hard",
    question: "How do RANK() and DENSE_RANK() differ?",
    answer: "RANK() leaves gaps after ties (1, 1, 3). DENSE_RANK() does not (1, 1, 2). Use RANK when the actual position matters, and DENSE_RANK() when you need consecutive rankings regardless of ties.",
    tags: ["RANK", "DENSE_RANK", "window function"],
    code: "-- Compare ranking strategies\nSELECT name, salary,\n       RANK() OVER (ORDER BY salary DESC) as rank,\n       DENSE_RANK() OVER (ORDER BY salary DESC) as dense_rank\nFROM employees;",
  },
  {
    id: "qa-win-03",
    category: "window-functions",
    difficulty: "hard",
    question: "How do I calculate running totals with window functions?",
    answer: "Use SUM() with OVER and ORDER BY to create running totals. The default frame is RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW. You can also use ROWS or RANGE to control the window frame precisely.",
    tags: ["running total", "SUM", "window function"],
    code: "-- Running total of sales by date\nSELECT date,\n       amount,\n       SUM(amount) OVER (ORDER BY date) as running_total\nFROM transactions\nORDER BY date;\n\n-- Moving average (last 3 transactions)\nSELECT date, amount,\n       AVG(amount) OVER (ORDER BY date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as moving_avg\nFROM transactions\nORDER BY date;",
  },
  {
    id: "qa-win-04",
    category: "window-functions",
    difficulty: "hard",
    question: "How do LAG() and LEAD() work?",
    answer: "LAG() accesses a previous row's value, LEAD() accesses a next row's value within the same result set. They're useful for comparing sequential rows, calculating deltas, and detecting changes.",
    tags: ["LAG", "LEAD", "window function"],
    code: "-- Compare each salary with the previous (lower) one\nSELECT name, salary,\n       LAG(salary) OVER (ORDER BY salary) as prev_salary,\n       salary - LAG(salary) OVER (ORDER BY salary) as diff\nFROM employees\nORDER BY salary;\n\n-- Day-over-day change\nSELECT date, amount,\n       LAG(amount) OVER (ORDER BY date) as prev_day,\n       ROUND((amount - LAG(amount) OVER (ORDER BY date)) / LAG(amount) OVER (ORDER BY date) * 100, 1) as pct_change\nFROM transactions\nORDER BY date;",
  },
  // CTE
  {
    id: "qa-cte-01",
    category: "cte-recursive",
    difficulty: "medium",
    question: "What is a CTE and why use it?",
    answer: "A CTE (Common Table Expression) is a temporary named result set that exists within a single query's scope. CTEs improve readability, allow referencing the same subquery multiple times, and are essential for recursive queries.",
    tags: ["CTE", "WITH", "readability"],
    code: "-- CTE for department averages, used in main query\nWITH dept_avg AS (\n  SELECT department, AVG(salary) as avg_sal\n  FROM employees\n  GROUP BY department\n)\nSELECT e.name, e.department, e.salary,\n       ROUND(da.avg_sal, 0) as dept_avg,\n       ROUND(e.salary - da.avg_sal, 0) as diff_from_avg\nFROM employees e\nJOIN dept_avg da ON e.department = da.department\nORDER BY diff_from_avg DESC;",
  },
  {
    id: "qa-cte-02",
    category: "cte-recursive",
    difficulty: "hard",
    question: "How do I build a recursive CTE for hierarchical data?",
    answer: "A recursive CTE has an anchor member (starting rows) and a recursive member (that references the CTE itself). The recursive member is repeatedly executed until it returns no rows. Use UNION ALL to combine results.",
    tags: ["recursive", "CTE", "hierarchy"],
    code: "-- Organizational hierarchy\nWITH RECURSIVE org_chain AS (\n  -- Anchor: top-level employees\n  SELECT id, name, manager_id, 0 as level, name as path\n  FROM employees WHERE manager_id IS NULL\n  \n  UNION ALL\n  \n  -- Recursive: direct reports\n  SELECT e.id, e.name, e.manager_id, oc.level + 1, oc.path || ' -> ' || e.name\n  FROM employees e\n  JOIN org_chain oc ON e.manager_id = oc.id\n)\nSELECT * FROM org_chain\nORDER BY level, name;",
  },
  {
    id: "qa-cte-03",
    category: "cte-recursive",
    difficulty: "medium",
    question: "Can I use multiple CTEs in one query?",
    answer: "Yes, separate CTEs with commas. Each CTE can reference previous ones. This makes complex queries modular and easier to debug — build your result step by step.",
    tags: ["CTE", "multiple"],
    code: "-- Multiple CTEs for step-by-step analysis\nWITH\nmonthly_sales AS (\n  SELECT strftime('%Y-%m', order_date) as month,\n         SUM(total) as revenue\n  FROM orders\n  GROUP BY month\n),\ntop_months AS (\n  SELECT * FROM monthly_sales\n  ORDER BY revenue DESC\n  LIMIT 3\n)\nSELECT * FROM top_months;",
  },
  // Performance
  {
    id: "qa-perf-01",
    category: "performance-tuning",
    difficulty: "medium",
    question: "Why is SELECT * bad for performance?",
    answer: "SELECT * retrieves all columns, which: (1) increases I/O and network transfer, (2) prevents index-only scans, (3) may break applications if table schema changes. Always select only the columns you need.",
    tags: ["SELECT *", "anti-pattern", "optimization"],
    code: "-- Bad: retrieves unnecessary columns\nSELECT * FROM employees WHERE department = 'Engineering';\n\n-- Good: only the columns you need\nSELECT name, salary, hire_date FROM employees WHERE department = 'Engineering';",
  },
  {
    id: "qa-perf-02",
    category: "performance-tuning",
    difficulty: "medium",
    question: "How do I identify slow queries?",
    answer: "Use EXPLAIN QUERY PLAN (SQLite) to see how the database executes a query. Look for full table scans (SCAN), missing indexes, and complex joins without proper keys. In production databases, use slow query logs.",
    tags: ["EXPLAIN", "slow query", "optimization"],
    code: "-- Check how SQLite executes a query\nEXPLAIN QUERY PLAN\nSELECT e.name, o.total\nFROM employees e\nJOIN orders o ON e.id = o.customer_id\nWHERE e.department = 'Engineering';\n\n-- Look for SCAN vs SEARCH in the output",
  },
  {
    id: "qa-perf-03",
    category: "performance-tuning",
    difficulty: "hard",
    question: "When should I create indexes?",
    answer: "Create indexes on columns used in WHERE clauses, JOIN conditions, and ORDER BY. Avoid over-indexing — each index slows down writes. For composite indexes, put high-selectivity columns first. Use covering indexes when possible.",
    tags: ["index", "optimization"],
    code: "-- Single column index for common filter\nCREATE INDEX idx_employees_dept ON employees(department);\n\n-- Composite index for multi-condition query\nCREATE INDEX idx_orders_customer_status ON orders(customer_id, status);\n\n-- Covering index (includes all selected columns)\nCREATE INDEX idx_employees_dept_covering ON employees(department, name, salary);",
  },
  // ETL Transforms
  {
    id: "qa-etl-01",
    category: "etl-transforms",
    difficulty: "medium",
    question: "How do I detect and remove duplicate rows?",
    answer: "Use ROW_NUMBER() with PARTITION BY on the dedup key, then delete rows with row_num > 1. For bulk ETL loads, use a staging table to dedup before inserting into the target.",
    tags: ["dedup", "ETL", "data quality"],
    code: "-- Find duplicates\nSELECT email, COUNT(*) as dup_count\nFROM employees\nGROUP BY email\nHAVING COUNT(*) > 1;\n\n-- Dedup with row_number (keep first occurrence)\nWITH deduped AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) as rn\n  FROM employees\n)\nSELECT * FROM deduped WHERE rn = 1;",
  },
  {
    id: "qa-etl-02",
    category: "etl-transforms",
    difficulty: "medium",
    question: "What is an upsert (MERGE) and how do I write one?",
    answer: "An upsert inserts a row if it doesn't exist, or updates it if it does. SQLite uses INSERT OR REPLACE (or INSERT ... ON CONFLICT DO UPDATE). PostgreSQL uses INSERT ... ON CONFLICT. This is essential for incremental ETL loads.",
    tags: ["MERGE", "upsert", "ETL"],
    code: "-- SQLite upsert\nINSERT INTO employees (id, name, department, salary, hire_date, email)\nVALUES (26, 'New Person', 'Engineering', 85000, '2024-03-01', 'new@example.com')\nON CONFLICT(id) DO UPDATE SET\n  name = excluded.name,\n  department = excluded.department,\n  salary = excluded.salary;",
  },
  {
    id: "qa-etl-03",
    category: "etl-transforms",
    difficulty: "hard",
    question: "How do I implement Change Data Capture (CDC) for incremental loads?",
    answer: "CDC tracks changes using timestamps, version numbers, or binary logs. Common patterns: (1) Last-modified timestamps on rows, (2) Incremental sequence numbers, (3) Change tracking tables, (4) Database triggers. Filter ETL queries to only process rows changed since the last run.",
    tags: ["CDC", "incremental", "ETL"],
    code: "-- Incremental load using timestamp\nSELECT * FROM orders\nWHERE updated_at > last_run_timestamp;\n\n-- Incremental using high-water mark\nINSERT INTO dw_orders\nSELECT o.*\nFROM staging_orders o\nLEFT JOIN dw_orders dw ON o.order_id = dw.order_id\nWHERE dw.order_id IS NULL;\n\n-- Version-based dedup (keep latest version)\nWITH latest AS (\n  SELECT *,\n         ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY version DESC) as rn\n  FROM staging_orders\n)\nSELECT * FROM latest WHERE rn = 1;",
  },
]
