import type { TroubleScenario } from "@/shared/types/content"

export const troubleScenarios: TroubleScenario[] = [
  {
    id: "conn-timeout",
    title: "Database Connection Timeout",
    category: "connection",
    description: "ETL pipeline fails to connect to source or target database with a timeout error.",
    icon: "Wifi",
    tree: {
      id: "q-root",
      question: "What error message are you seeing?",
      answers: [
        {
          id: "a-timeout",
          label: "Connection timed out",
          next: {
            id: "q-timeout",
            question: "Can you reach the database host from the ETL server?",
            answers: [
              {
                id: "a-ping-fail",
                label: "No, cannot ping/host unreachable",
                next: {
                  id: "sol-firewall",
                  isSolution: true,
                  title: "Firewall or Network Issue",
                  description: "The ETL server cannot reach the database host. This is usually a network/firewall configuration issue.",
                  steps: [
                    "Verify the database hostname/IP address in your connection config",
                    "Check if the database port is open: `telnet <host> <port>` or `nc -zv <host> <port>`",
                    "Review firewall rules on both the ETL server and database server",
                    "Ensure security groups (AWS) or firewall policies allow inbound traffic from the ETL server IP",
                    "Check if the database is bound to 0.0.0.0 (all interfaces) or only localhost",
                    "Verify DNS resolution: `nslookup <hostname>`",
                    "If using a VPN, ensure the VPN tunnel is active and configured correctly",
                  ],
                  codeExample: "# Test connectivity from command line\ntelnet my-db-host.example.com 5432\n# Expected: Connected to <host>\n\n# Check DNS resolution\nnslookup my-db-host.example.com\n\n# Check if port is open (Linux/Mac)\nnc -zv my-db-host.example.com 5432",
                  preventionTips: [
                    "Document all network dependencies with port numbers",
                    "Set up synthetic monitoring to test connectivity proactively",
                    "Use connection strings with retry logic",
                    "Configure proper security groups with infrastructure-as-code",
                  ],
                },
              },
              {
                id: "a-ping-ok",
                label: "Yes, host is reachable",
                next: {
                  id: "q-cred",
                  question: "Are the credentials correct?",
                  answers: [
                    {
                      id: "a-cred-no",
                      label: "Not sure / credentials might be wrong",
                      next: {
                        id: "sol-creds",
                        isSolution: true,
                        title: "Invalid Database Credentials",
                        description: "The connection is being rejected due to incorrect username, password, or authentication method.",
                        steps: [
                          "Reset the database user password and update the ETL connection string",
                          "Verify the username exists and has CONNECT privilege on the database",
                          "Check if the password contains special characters that need URL-encoding",
                          "Verify the authentication method (password, SSPI, IAM) is supported by both sides",
                          "Check if the database user is locked or expired",
                          "Test connection with a simple SQL client (psql, DBeaver) using same credentials",
                          "If using SSL/TLS, verify certificates are valid and not expired",
                        ],
                        codeExample: "# Test connection with psql\npsql -h hostname -U username -d database -W\n# Or with environment variables\nPGPASSWORD=<password> psql -h hostname -U username -d database",
                        preventionTips: [
                          "Use a secrets manager (AWS Secrets Manager, HashiCorp Vault) for credentials",
                          "Rotate database passwords on a regular schedule",
                          "Use IAM-based authentication when available",
                          "Test credentials as part of your CI/CD pipeline",
                        ],
                      },
                    },
                    {
                      id: "a-cred-yes",
                      label: "Yes, credentials are correct",
                      next: {
                        id: "q-resource",
                        question: "Is the database under heavy load or out of connections?",
                        answers: [
                          {
                            id: "a-resource-yes",
                            label: "Yes, high load / max connections reached",
                            next: {
                              id: "sol-resource",
                              isSolution: true,
                              title: "Database Resource Exhaustion",
                              description: "The database has reached its maximum connection limit or is under heavy load causing timeouts.",
                              steps: [
                                "Check current connection count: `SELECT count(*) FROM pg_stat_activity;` (PostgreSQL)",
                                "Increase max_connections in database config and restart",
                                "Implement connection pooling (PgBouncer, HikariCP) between ETL and database",
                                "Add resource alerts at 80% of max connections",
                                "Optimize ETL to use fewer concurrent connections",
                                "Schedule heavy ETL jobs during off-peak hours",
                                "Consider scaling up the database instance",
                              ],
                              codeExample: "-- PostgreSQL: check connection count\nSELECT state, COUNT(*) FROM pg_stat_activity GROUP BY state;\n\n-- Check max_connections setting\nSHOW max_connections;\n\n-- Kill idle connections (use cautiously)\nSELECT pg_terminate_backend(pid) FROM pg_stat_activity\nWHERE state = 'idle' AND pid <> pg_backend_pid();",
                              preventionTips: [
                                "Set up connection pool limits in your ETL tool",
                                "Monitor database connections and set alerts",
                                "Implement exponential backoff in retry logic",
                                "Size your database instance for peak load plus headroom",
                              ],
                            },
                          },
                          {
                            id: "a-resource-no",
                            label: "No, database is responsive",
                            next: {
                              id: "sol-driver",
                              isSolution: true,
                              title: "Driver or Connection String Issue",
                              description: "The JDBC/ODBC driver or connection string format may be incorrect.",
                              steps: [
                                "Verify you're using the correct JDBC driver version for your database version",
                                "Check the connection string format for your specific driver",
                                "Ensure the driver JAR is in the ETL tool's classpath",
                                "Test with a minimal connection string",
                                "Check for SSL/TLS configuration mismatches",
                                "Try connecting with a different client tool to isolate the issue",
                              ],
                              codeExample: "# PostgreSQL JDBC connection string format\njdbc:postgresql://host:5432/database?sslmode=require\n\n# MySQL JDBC connection string\njdbc:mysql://host:3306/database?useSSL=true&serverTimezone=UTC\n\n# Check installed driver version\ndpkg -l | grep -i postgresql\n# or\npip list | grep psycopg",
                              preventionTips: [
                                "Standardize connection strings in a config management system",
                                "Pin driver versions in your ETL deployment",
                                "Test driver compatibility during upgrades in a staging environment",
                              ],
                            },
                          },
                        ],
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
        {
          id: "a-auth-fail",
          label: "Authentication failed",
          next: {
            id: "sol-auth",
            isSolution: true,
            title: "Authentication Failure",
            description: "The database rejected the provided credentials.",
            steps: [
              "Verify the username exists in the database",
              "Reset the password and update all connection strings",
              "Check if the user has been locked out due to failed attempts",
              "Verify the authentication method (md5, scram-sha-256, password) is supported",
              "If using SSL client certificates, verify they haven't expired",
              "Check if the user is allowed to connect from the ETL server's IP address (pg_hba.conf)",
            ],
            preventionTips: [
              "Use a centralized secrets manager",
              "Set up credential rotation automation",
              "Monitor for authentication failures in database logs",
            ],
          },
        },
      ],
    },
  },
  {
    id: "data-quality-nulls",
    title: "Unexpected NULL Values",
    category: "data-quality",
    description: "ETL process fails or produces incorrect results due to unexpected NULL values in source data.",
    icon: "AlertTriangle",
    tree: {
      id: "dq-root",
      question: "Where are the NULL values appearing?",
      answers: [
        {
          id: "dq-key",
          label: "In key/join columns",
          next: {
            id: "sol-dq-key",
            isSolution: true,
            title: "NULL Values in Key Columns",
            description: "NULL values in JOIN keys or primary key columns can cause data loss and incorrect results.",
            steps: [
              "Identify which columns have unexpected NULLs: `SELECT COUNT(*) FROM table WHERE key_col IS NULL;`",
              "Determine if NULLs are valid business values or data quality issues",
              "For valid NULLs in JOINs, use COALESCE to provide a sentinel value",
              "For invalid NULLs, investigate the source system data entry process",
              "Add NOT NULL constraints to prevent future occurrences",
              "Implement data quality checks at the extract stage to catch NULL keys early",
              "Consider if NULL key rows should be quarantined or processed separately",
            ],
            codeExample: "-- Find NULLs in key columns\nSELECT COUNT(*) FROM orders WHERE customer_id IS NULL;\n\n-- Use COALESCE for safe JOINs\nSELECT *\nFROM orders o\nLEFT JOIN customers c ON o.customer_id = c.customer_id\nWHERE o.customer_id IS NOT NULL;  -- Exclude NULL-keyed orders\n\n-- Quarantine NULL-keyed rows\nINSERT INTO error_orders (order_id, raw_data, error_reason)\nSELECT order_id, 'missing customer', 'NULL customer_id'\nFROM staging_orders WHERE customer_id IS NULL;",
            preventionTips: [
              "Add NOT NULL constraints to critical columns in staging tables",
              "Implement data quality checks at source extraction",
              "Set up monitoring for NULL rate changes in key columns",
              "Document allowed NULL patterns for each data source",
            ],
          },
        },
        {
          id: "dq-measure",
          label: "In measure/numeric columns",
          next: {
            id: "sol-dq-measure",
            isSolution: true,
            title: "NULL Values in Measure Columns",
            description: "NULL values in numeric columns can cause aggregation errors (AVG, SUM) and reporting issues.",
            steps: [
              "Check for NULLs in numeric columns: `SELECT COUNT(*) FROM table WHERE amount IS NULL;`",
              "Use COALESCE or IFNULL to provide defaults: `COALESCE(amount, 0)`",
              "Be aware that AVG() ignores NULLs but SUM() treats them as 0—determine the right behavior",
              "Create a data quality check to flag NULL rates above a threshold",
              "Investigate source system to understand why NULLs are generated",
              "Consider if rows with NULL measures should be excluded or included with defaults",
            ],
            codeExample: "-- Profile NULLs in numeric columns\nSELECT\n  COUNT(*) as total,\n  SUM(CASE WHEN amount IS NULL THEN 1 ELSE 0 END) as null_amounts,\n  ROUND(AVG(CASE WHEN amount IS NOT NULL THEN amount END), 2) as avg_excl_nulls,\n  ROUND(AVG(COALESCE(amount, 0)), 2) as avg_with_default\nFROM transactions;\n\n-- Safe aggregation\nSELECT category,\n  COUNT(*) as count,\n  AVG(COALESCE(amount, 0)) as avg_amount,\n  SUM(COALESCE(amount, 0)) as total_amount\nFROM transactions\nGROUP BY category;",
            preventionTips: [
              "Document whether NULLs in numeric columns represent 0 or unknown",
              "Set up alerts when NULL percentage exceeds normal range",
              "Use DEFAULT values in target tables to handle NULLs consistently",
            ],
          },
        },
        {
          id: "dq-text",
          label: "In text/string columns",
          next: {
            id: "sol-dq-text",
            isSolution: true,
            title: "NULL Values in Text Columns",
            description: "NULL values in text columns can cause string concatenation errors, reporting 'blanks', and application issues.",
            steps: [
              "Understand if NULL vs empty string ('') have different meanings in your data",
              "Use COALESCE for display: `COALESCE(description, 'No description')`",
              "Normalize NULL to empty string if they're treated the same by downstream systems",
              "Check for leading/trailing whitespace that might make strings appear non-empty",
              "Add validation rules at the ETL transform stage",
            ],
            codeExample: "-- Handle NULL text values\nSELECT\n  name,\n  COALESCE(email, 'no-email') as email,\n  CASE WHEN description IS NULL THEN '' ELSE description END as description\nFROM employees;\n\n-- Find empty vs NULL\nSELECT\n  COUNT(*) as total,\n  SUM(CASE WHEN email IS NULL THEN 1 ELSE 0 END) as null_emails,\n  SUM(CASE WHEN email = '' THEN 1 ELSE 0 END) as empty_emails\nFROM employees;",
            preventionTips: [
              "Standardize on NULL vs empty string policy across all data sources",
              "Use data dictionaries to document field-level NULL semantics",
              "Implement standardization rules in your ETL transform layer",
            ],
          },
        },
      ],
    },
  },
  {
    id: "dup-records",
    title: "Duplicate Records in Target",
    category: "data-quality",
    description: "Duplicate rows appear in the target table after ETL load, causing incorrect aggregations and reports.",
    icon: "Copy",
    tree: {
      id: "dup-root",
      question: "When do the duplicates appear?",
      answers: [
        {
          id: "dup-incremental",
          label: "After incremental loads",
          next: {
            id: "sol-dup-incremental",
            isSolution: true,
            title: "Duplicate Records from Incremental Loads",
            description: "Incremental loads are re-inserting already-loaded records due to incorrect high-water mark tracking or missing dedup logic.",
            steps: [
              "Check if your incremental load watermark (max ID, max timestamp) is being correctly tracked",
              "Verify the watermark table/state is being persisted between runs",
              "Implement an upsert (MERGE) pattern instead of INSERT-only for incremental loads",
              "Add a pre-load dedup step to remove already-existing records from the batch",
              "Check if the source system is sending the same records in multiple batches",
              "Add unique constraints/indexes to the target table to catch duplicates",
            ],
            codeExample: "-- Check for duplicates after load\nSELECT order_id, COUNT(*) as dup_count\nFROM target_orders\nGROUP BY order_id\nHAVING COUNT(*) > 1;\n\n-- Upsert pattern (SQLite)\nINSERT INTO target_orders (order_id, customer_id, total, order_date)\nSELECT order_id, customer_id, total, order_date\nFROM staging_orders\nON CONFLICT(order_id) DO UPDATE SET\n  total = excluded.total,\n  order_date = excluded.order_date;",
            preventionTips: [
              "Always use UPSERT/MERGE for incremental loads on tables with natural keys",
              "Persist watermarks in a dedicated control table",
              "Add row count comparisons between source and target after each load",
              "Monitor for sudden changes in row counts that might indicate duplicates",
            ],
          },
        },
        {
          id: "dup-full",
          label: "After full refresh loads",
          next: {
            id: "sol-dup-full",
            isSolution: true,
            title: "Duplicate Records from Full Refresh",
            description: "Full refresh did not properly truncate before inserting, or multiple ETL jobs are writing to the same table concurrently.",
            steps: [
              "Verify the truncate step completed successfully before the insert phase",
              "Check if multiple ETL instances are running concurrently",
              "Ensure the full refresh is wrapped in a transaction: TRUNCATE + INSERT in one transaction",
              "Check if the load job is idempotent—running it twice should produce the same result",
              "Review the ETL job scheduling to prevent overlap",
              "Add a pre-load check: target table should be empty before full refresh",
            ],
            codeExample: "-- Proper full refresh pattern (in transaction)\nBEGIN TRANSACTION;\n  DELETE FROM target_orders; -- Or TRUNCATE if supported\n  INSERT INTO target_orders\n  SELECT * FROM staging_orders\n  WHERE load_date = CURRENT_DATE;\nCOMMIT;\n\n-- Pre-load emptiness check\nSELECT COUNT(*) as row_count FROM target_orders;",
            preventionTips: [
              "Always use transactions for truncate+insert patterns",
              "Implement job concurrency checks to prevent overlapping runs",
              "Use idempotent load patterns so re-runs don't create duplicates",
              "Set up ETL job monitoring with alerts for unexpected behavior",
            ],
          },
        },
      ],
    },
  },
  {
    id: "type-mismatch",
    title: "Data Type Mismatch on Load",
    category: "schema",
    description: "ETL load fails because source data types don't match target column definitions.",
    icon: "Table2",
    tree: {
      id: "tm-root",
      question: "What type of mismatch is occurring?",
      answers: [
        {
          id: "tm-numeric",
          label: "Numeric/Decimal mismatch",
          next: {
            id: "sol-tm-numeric",
            isSolution: true,
            title: "Numeric Type Mismatch",
            description: "Source data contains numeric values that don't fit the target column precision/scale or contain non-numeric characters.",
            steps: [
              "Examine the source data: `SELECT DISTINCT typeof(column) FROM source_table`",
              "Check for non-numeric characters in numeric fields (commas, currency symbols, spaces)",
              "Verify precision/scale: source decimal(10,2) vs target decimal(8,2) can overflow",
              "Use CAST or CONVERT to explicitly handle type conversion",
              "For string-to-number conversion, clean the data first by removing non-numeric characters",
              "Consider staging all data as TEXT and then converting with explicit validation",
            ],
            codeExample: "-- Check for non-numeric values\nSELECT amount FROM staging\nWHERE amount REGEXP '[^0-9\\.\\-]';\n\n-- Clean and convert\nSELECT\n  CASE\n    WHEN amount REGEXP '^[0-9\\.]+$' THEN CAST(amount AS REAL)\n    ELSE NULL\n  END as clean_amount\nFROM staging;\n\n-- Safe numeric conversion\nSELECT CAST(REPLACE(REPLACE(amount, ',', ''), '$', '') AS REAL)\nFROM staging;",
            preventionTips: [
              "Define clear data type mappings in your ETL design document",
              "Validate source data types before each load",
              "Use a staging layer where all columns are TEXT for initial loading, then convert explicitly",
              "Set up type validation rules in your data quality framework",
            ],
          },
        },
        {
          id: "tm-date",
          label: "Date/Timestamp mismatch",
          next: {
            id: "sol-tm-date",
            isSolution: true,
            title: "Date/Time Type Mismatch",
            description: "Source date formats don't match target expectations, or invalid date values exist in the source.",
            steps: [
              "Identify the date formats in the source data",
              "Use date parsing functions to standardize: `strftime`, `TO_DATE`, `CONVERT`",
              "Check for invalid dates (Feb 30, 13th month, zero values like '0000-00-00')",
              "Handle timezone conversions explicitly",
              "For unknown/invalid dates, use NULL or a sentinel value (1900-01-01)",
              "Standardize all dates to ISO 8601 format (YYYY-MM-DD) in staging",
            ],
            codeExample: "-- Parse various date formats\nSELECT\n  CASE\n    WHEN order_date LIKE '__/__/____' THEN\n      SUBSTR(order_date, 7, 4) || '-' || SUBSTR(order_date, 1, 2) || '-' || SUBSTR(order_date, 4, 2)\n    WHEN order_date LIKE '____-__-__' THEN\n      order_date\n    ELSE NULL\n  END as clean_date\nFROM staging;\n\n-- SQLite date parsing\nSELECT DATE(order_date) as parsed_date\nFROM staging\nWHERE order_date IS NOT NULL;",
            preventionTips: [
              "Standardize all dates to ISO 8601 at the earliest stage of the pipeline",
              "Document expected date formats for each source system",
              "Add date format validation checks at the extract stage",
              "Use date libraries (Python dateutil, Java Joda-Time) for flexible parsing",
            ],
          },
        },
      ],
    },
  },
  {
    id: "slow-incremental",
    title: "Slow Incremental Load Performance",
    category: "performance",
    description: "Incremental ETL loads are taking progressively longer, approaching the batch window limit.",
    icon: "Clock",
    tree: {
      id: "slow-root",
      question: "How is the incremental load implemented?",
      answers: [
        {
          id: "slow-timestamp",
          label: "Timestamp-based filtering",
          next: {
            id: "q-slow-index",
            question: "Is there an index on the timestamp column?",
            answers: [
              {
                id: "slow-no-index",
                label: "No index",
                next: {
                  id: "sol-slow-index",
                  isSolution: true,
                  title: "Missing Index on Timestamp Column",
                  description: "Full table scans on the source/target table cause progressively slower performance as data grows.",
                  steps: [
                    "Add an index on the timestamp column used for incremental filtering",
                    "Consider a composite index on (timestamp, id) for range queries",
                    "Verify the index is being used: run EXPLAIN QUERY PLAN on the incremental query",
                    "For large tables, consider table partitioning by date",
                    "If using UUIDs, consider a BRIN index instead of default B-tree",
                    "Analyze table statistics after creating indexes",
                  ],
                  codeExample: "-- Check index usage\nEXPLAIN QUERY PLAN\nSELECT * FROM orders WHERE order_date > '2024-01-01';\n\n-- Create index on timestamp\nCREATE INDEX idx_orders_date ON orders(order_date);\n\n-- Composite index for common query pattern\nCREATE INDEX idx_orders_date_id ON orders(order_date, order_id);\n\n-- Check table size to understand data growth\nSELECT COUNT(*) as row_count FROM orders;",
                  preventionTips: [
                    "Add indexes as part of the initial ETL setup, not as an afterthought",
                    "Monitor query performance and index usage regularly",
                    "Review table growth trends to proactively plan for performance scaling",
                  ],
                },
              },
              {
                id: "slow-has-index",
                label: "Yes, index exists",
                next: {
                  id: "sol-slow-watermark",
                  isSolution: true,
                  title: "Inefficient Watermark Management",
                  description: "The incremental load is processing too much data per run due to a large or mismanaged watermark range.",
                  steps: [
                    "Check the watermark value being used for the current run",
                    "Verify the watermark is being updated correctly after each successful load",
                    "Consider micro-batching: smaller, more frequent incremental loads",
                    "Check if data is arriving late (late-arriving facts) requiring re-processing of older periods",
                    "Implement parallel extraction if the source supports it",
                    "Consider changing from timestamp-based to ID-based incremental loading",
                  ],
                  codeExample: "-- Check current watermark\nSELECT * FROM etl_watermarks WHERE table_name = 'orders';\n\n-- Micro-batch: smaller increments\nSELECT * FROM orders\nWHERE order_date > '2024-01-01'\nAND order_date <= '2024-01-02';  -- One day at a time\n\n-- ID-based watermark (more efficient)\nSELECT * FROM orders\nWHERE order_id > 100000\nORDER BY order_id\nLIMIT 10000;",
                  preventionTips: [
                    "Monitor incremental load row counts and alert on sudden increases",
                    "Consider micro-batching for high-volume tables",
                    "Implement late-arriving data handling strategies",
                    "Regularly review and optimize watermark management",
                  ],
                },
              },
            ],
          },
        },
        {
          id: "slow-full-scan",
          label: "Full table scan / no filter",
          next: {
            id: "sol-slow-redesign",
            isSolution: true,
            title: "Redesign to Proper Incremental Load",
            description: "The ETL is performing full table scans on every run because there's no incremental filtering logic.",
            steps: [
              "Identify a column that can serve as a watermark (updated_at timestamp, auto-incrementing ID)",
              "Create a watermark tracking table or file to persist last-run state",
              "Modify the extract query to filter: `WHERE updated_at > last_watermark`",
              "For tables with no timestamp columns, consider: triggers, CDC tools, or version-based extraction",
              "If the source database supports it, enable Change Data Capture (CDC) features",
              "Test the incremental load with historical data to verify correctness",
              "Implement a reconciliation step: compare row counts between full and incremental to verify accuracy",
            ],
            codeExample: "-- Watermark tracking table\nCREATE TABLE etl_watermarks (\n  table_name TEXT PRIMARY KEY,\n  last_max_id INTEGER,\n  last_max_timestamp TEXT,\n  updated_at TEXT DEFAULT CURRENT_TIMESTAMP\n);\n\n-- Update watermark after load\nINSERT INTO etl_watermarks (table_name, last_max_id, last_max_timestamp)\nVALUES ('orders', 50000, '2024-06-14 10:30:00')\nON CONFLICT(table_name) DO UPDATE SET\n  last_max_id = excluded.last_max_id,\n  last_max_timestamp = excluded.last_max_timestamp,\n  updated_at = CURRENT_TIMESTAMP;",
            preventionTips: [
              "Design incremental loading from the start—don't add it as an afterthought",
              "Choose watermark columns that are indexed and monotonically increasing",
              "Test incremental loads thoroughly with a representative data volume",
              "Have monitoring in place to detect when incremental is falling behind",
            ],
          },
        },
      ],
    },
  },
  {
    id: "schema-drift",
    title: "Schema Drift Detection",
    category: "schema",
    description: "Source table schema has changed (new columns, dropped columns, type changes), causing ETL failures.",
    icon: "GitBranch",
    tree: {
      id: "sd-root",
      question: "What type of schema change occurred?",
      answers: [
        {
          id: "sd-new-col",
          label: "New column added to source",
          next: {
            id: "sol-sd-new-col",
            isSolution: true,
            title: "New Column in Source Table",
            description: "A new column was added to the source table that ETL mapping doesn't account for.",
            steps: [
              "Identify the new column name and data type",
              "Determine if the new column should be included in the ETL process",
              "If needed, add the column to the target table: ALTER TABLE target ADD COLUMN ...",
              "Update ETL mapping to include the new column",
              "If not needed, update the ETL to explicitly ignore new columns via column whitelist",
              "Consider implementing schema drift detection to alert on changes automatically",
              "Add column count/shape validation in ETL pre-checks",
            ],
            codeExample: "-- Compare source and target schemas\nPRAGMA table_info('source_orders');\nPRAGMA table_info('target_orders');\n\n-- Add missing column to target\nALTER TABLE target_orders ADD COLUMN discount REAL;",
            preventionTips: [
              "Implement schema drift detection using column count and name checks",
              "Use column whitelists instead of SELECT * in ETL queries",
              "Add schema validation as the first step of every ETL pipeline",
              "Set up notifications for any schema change detection",
              "Maintain a schema registry or data catalog",
            ],
          },
        },
        {
          id: "sd-drop-col",
          label: "Column dropped from source",
          next: {
            id: "sol-sd-drop-col",
            isSolution: true,
            title: "Column Dropped from Source Table",
            description: "A column that was previously extracted is no longer present in the source.",
            steps: [
              "Check if the column was renamed (not dropped) by comparing old and new column lists",
              "If truly dropped, determine if a replacement column exists",
              "If the column is optional, update ETL mappings to use NULL as default",
              "Update any downstream transformations that reference the dropped column",
              "Check for downstream impact: reports, dashboards, and applications using this data",
              "Document the change and notify data consumers",
            ],
            codeExample: "-- Check for missing columns\nSELECT col_name FROM expected_columns\nWHERE col_name NOT IN (\n  SELECT name FROM pragma_table_info('source_table')\n);\n\n-- Use COALESCE to handle potentially missing columns dynamically\nSELECT COALESCE(dropped_column, 'N/A') as col FROM source_table;",
            preventionTips: [
              "Implement a column existence check before ETL extraction queries",
              "Use a data catalog to track schema changes and their impact",
              "Set up automated alerts when column count or names change",
              "Build ETL mappings that can gracefully handle optional columns",
            ],
          },
        },
      ],
    },
  },
  {
    id: "high-memory",
    title: "High Memory Usage / OOM Errors",
    category: "performance",
    description: "ETL process crashes with out-of-memory errors during large data transformations.",
    icon: "MemoryStick",
    tree: {
      id: "mem-root",
      question: "When does the OOM occur?",
      answers: [
        {
          id: "mem-join",
          label: "During JOIN operations",
          next: {
            id: "sol-mem-join",
            isSolution: true,
            title: "Memory Exhaustion During JOINs",
            description: "Large in-memory JOINs between unsorted/unindexed tables cause excessive memory consumption.",
            steps: [
              "Ensure both sides of the JOIN have indexes on the join keys",
              "Break the JOIN into smaller batches using WHERE clauses",
              "Use incremental/batched processing: process data in chunks (e.g., by date)",
              "Check for Cartesian products caused by missing JOIN conditions",
              "Consider using a database engine for large JOINs instead of in-memory processing",
              "Increase available memory or use external sorting/joining algorithms",
            ],
            codeExample: "-- Check for Cartesian product (dangerous!)\nEXPLAIN QUERY PLAN\nSELECT * FROM large_table_a, large_table_b  -- Missing ON clause!\nWHERE a.id = b.id;\n\n-- Batch processing pattern\nSELECT * FROM large_table_a a\nJOIN large_table_b b ON a.id = b.id\nWHERE a.id BETWEEN 1 AND 10000;  -- Process in batches",
            preventionTips: [
              "Always verify JOIN conditions are correct and specific",
              "Use batched processing for large datasets",
              "Monitor memory usage during ETL runs and set resource limits",
              "Use database-level JOINs instead of in-memory when possible",
            ],
          },
        },
        {
          id: "mem-group",
          label: "During GROUP BY / sorting",
          next: {
            id: "sol-mem-group",
            isSolution: true,
            title: "Memory Exhaustion During Aggregation",
            description: "GROUP BY on high-cardinality columns or sorting large datasets in memory causes OOM.",
            steps: [
              "Check the cardinality of the GROUP BY columns—high cardinality needs more memory",
              "Reduce the number of rows being aggregated: filter earlier, aggregate smaller batches",
              "Consider pre-aggregating data before the ETL (push-down aggregation to source database)",
              "Use approximate aggregation algorithms when exact precision isn't needed",
              "Sort on disk instead of in-memory if your processing engine supports it",
              "Increase the sort/aggregation memory buffer or spill-to-disk settings",
            ],
            codeExample: "-- Check GROUP BY cardinality\nSELECT COUNT(DISTINCT user_id) FROM transactions;\n-- If > 1M, consider batch aggregation\n\n-- Pre-aggregation (push-down)\nSELECT user_id, SUM(amount) as total\nFROM source_transactions\nWHERE date >= '2024-01-01'\nGROUP BY user_id;  -- Aggregate in source DB, not in ETL memory",
            preventionTips: [
              "Push down aggregations to source databases when possible",
              "Use incremental aggregation for high-cardinality dimensions",
              "Monitor group-by key cardinality and set up alerts for unusual growth",
              "Configure appropriate memory limits for sort/aggregation operations",
            ],
          },
        },
      ],
    },
  },
  {
    id: "circular-dependency",
    title: "Circular Dependency in Pipeline",
    category: "dependency",
    description: "ETL pipeline jobs reference each other in a cycle, preventing any job from starting.",
    icon: "RefreshCw",
    tree: {
      id: "cd-root",
      question: "How was the circular dependency detected?",
      answers: [
        {
          id: "cd-dag",
          label: "DAG scheduler (Airflow, Dagster) reported it",
          next: {
            id: "sol-cd-dag",
            isSolution: true,
            title: "Circular Dependency in Job DAG",
            description: "Your pipeline scheduler has detected that job dependencies form a cycle that cannot be resolved.",
            steps: [
              "List all upstream/downstream dependencies for the jobs in the cycle",
              "Identify unnecessary dependencies that can be removed",
              "Break the cycle by: removing a dependency, introducing a new intermediate table, or restructuring the pipeline",
              "Consider adding a new staging layer that both cycles read from instead of depending on each other",
              "Rename/restructure pipeline stages to clarify data flow direction",
              "After fixing, validate the DAG is now a directed acyclic graph (DAG)",
              "Document the pipeline structure clearly to prevent regression",
            ],
            codeExample: "# Airflow: check task dependencies\nairflow tasks list dag_id --tree\n\n# If A -> B -> C -> A, restructure to:\n# A -> B -> C (C writes to shared table)\n# A reads from shared table instead of from C directly",
            preventionTips: [
              "Use a DAG visualization tool to review dependencies before deployment",
              "Enforce a clear pipeline stage structure (Extract -> Transform -> Load)",
              "Code review DAG changes with attention to dependency direction",
              "Document data lineage so dependency direction is clear",
            ],
          },
        },
        {
          id: "cd-data",
          label: "Data loading is stuck in a loop",
          next: {
            id: "sol-cd-data",
            isSolution: true,
            title: "Data-Level Circular Reference",
            description: "Two tables reference each other via foreign keys, causing load order issues.",
            steps: [
              "Temporarily disable foreign key constraints to break the cycle",
              "Load one table first with NULL foreign keys",
              "Load the second table with its foreign keys",
              "Update the first table's foreign keys in a third pass",
              "Alternatively, defer constraint checking until both tables are loaded",
              "As a long-term fix, consider if the circular reference can be redesigned",
            ],
            codeExample: "-- Load order for circular FK reference\n-- Step 1: Disable FK checks\nPRAGMA foreign_keys = OFF;\n\n-- Step 2: Load both tables\nINSERT INTO table_a ...\nINSERT INTO table_b ...\n\n-- Step 3: Update FKs\nUPDATE table_a SET ref_b_id = (SELECT id FROM table_b WHERE ...);\n\n-- Step 4: Re-enable\nPRAGMA foreign_keys = ON;",
            preventionTips: [
              "Avoid circular foreign key references in database design when possible",
              "Use deferred constraint checking if your database supports it",
              "Document all foreign key relationships and their load order requirements",
              "Consider denormalizing to break circular references",
            ],
          },
        },
      ],
    },
  },
  {
    id: "data-skew",
    title: "Data Skew in Distributed Processing",
    category: "performance",
    description: "Some workers/partitions take much longer than others due to uneven data distribution.",
    icon: "BarChart3",
    tree: {
      id: "skew-root",
      question: "Which operation shows the skew?",
      answers: [
        {
          id: "skew-join",
          label: "JOIN operation is skewed",
          next: {
            id: "sol-skew-join",
            isSolution: true,
            title: "Skewed JOIN Key Distribution",
            description: "Some JOIN key values have much more data than others, overloading specific partitions.",
            steps: [
              "Identify skewed keys: `SELECT key, COUNT(*) FROM table GROUP BY key ORDER BY COUNT(*) DESC LIMIT 10;`",
              "For highly-skewed keys (e.g., NULL, default values), separate them into their own processing path",
              "Use salting: add a random prefix to skewed keys to distribute data across more partitions",
              "Use a broadcast JOIN for small tables to avoid shuffling",
              "Configure your processing engine's skew join handling (Spark AQE skew join optimization)",
              "Process skewed keys in a separate, dedicated task",
            ],
            codeExample: "-- Find skewed keys\nSELECT department, COUNT(*) as cnt\nFROM employees\nGROUP BY department\nORDER BY cnt DESC;\n\n-- Salting technique (Spark-style)\n-- Add salt to skewed key: CONCAT(key, '_', FLOOR(RAND() * 10))\n-- Process in two phases: join with salt, then aggregate results",
            preventionTips: [
              "Analyze key distribution before designing JOIN-heavy pipelines",
              "Handle NULL/default keys separately with dedicated processing",
              "Enable automatic skew join optimization in your processing engine",
              "Monitor partition sizes during processing to detect skew early",
            ],
          },
        },
        {
          id: "skew-group",
          label: "GROUP BY / aggregation is skewed",
          next: {
            id: "sol-skew-group",
            isSolution: true,
            title: "Skewed Aggregation Key Distribution",
            description: "Some GROUP BY key values dominate the data, overloading single partitions.",
            steps: [
              "Profile the GROUP BY key distribution",
              "Apply two-phase aggregation: partial aggregation with salting, then merge results",
              "Use an approximate aggregation algorithm for high-cardinality or skewed keys",
              "Filter out dominating keys and process them separately if possible",
              "Consider bucketing by a secondary key to distribute data more evenly",
            ],
            codeExample: "-- Two-phase aggregation for skewed keys\n-- Phase 1: Partial aggregations with salt\nSELECT CONCAT(category, '_', FLOOR(RAND() * 10)) as salted_key,\n       SUM(amount) as partial_total\nFROM transactions\nGROUP BY salted_key;\n\n-- Phase 2: Final aggregation\nSELECT SPLIT(salted_key, '_')[1] as category,\n       SUM(partial_total) as total\nFROM phase1_results\nGROUP BY category;",
            preventionTips: [
              "Profile key distribution during development",
              "Use two-phase aggregation when key skew is expected",
              "Consider using bucketed/salted keys in high-skew scenarios",
              "Enable automatic skew handling in your processing framework",
            ],
          },
        },
      ],
    },
  },
  {
    id: "job-ordering",
    title: "Job Dependency Order Violation",
    category: "dependency",
    description: "ETL jobs are executing in the wrong order, causing downstream jobs to read incomplete or stale data.",
    icon: "ListOrdered",
    tree: {
      id: "jo-root",
      question: "How are you managing job dependencies?",
      answers: [
        {
          id: "jo-manual",
          label: "Manual triggers / cron jobs",
          next: {
            id: "sol-jo-manual",
            isSolution: true,
            title: "Manual Job Scheduling Issues",
            description: "Manually triggered or cron-based jobs have no dependency management, leading to ordering issues.",
            steps: [
              "Implement a proper job scheduler (Airflow, Dagster, Prefect) to manage dependencies",
              "If staying with cron, add explicit completion checks at the start of each job",
              "Use a status table that jobs update on completion, check before starting",
              "Add sufficient buffer time between dependent jobs' scheduled times",
              "Implement job-level retry with exponential backoff",
              "Set up monitoring to alert when job order violations occur",
            ],
            codeExample: "-- Completion check table\nCREATE TABLE job_status (\n  job_name TEXT PRIMARY KEY,\n  last_successful_run TEXT,\n  status TEXT CHECK(status IN ('running', 'completed', 'failed'))\n);\n\n-- Check upstream before starting\nSELECT status FROM job_status\nWHERE job_name = 'extract_orders'\nAND last_successful_run >= '2024-01-01';",
            preventionTips: [
              "Migrate from cron to a DAG-based scheduler for complex pipelines",
              "Implement job status tracking from day one",
              "Set up monitoring and alerts for job ordering violations",
              "Build idempotent jobs that can be safely re-run",
            ],
          },
        },
        {
          id: "jo-scheduler",
          label: "Using a DAG scheduler (Airflow etc.)",
          next: {
            id: "sol-jo-scheduler",
            isSolution: true,
            title: "DAG Scheduler Configuration Issues",
            description: "The scheduler is running tasks out of order due to misconfigured dependencies, wrong schedule intervals, or missing upstream triggers.",
            steps: [
              "Verify the task dependency chain: `airflow tasks list dag_id --tree`",
              "Check that all upstream tasks are configured with `depends_on_past: False` if they should run independently",
              "Ensure the DAG schedule interval is consistent for all tasks in the DAG",
              "Look for missing `>>` or `<<` dependency operators in the DAG definition",
              "Check if some tasks have `trigger_rule='all_done'` allowing them to run even on upstream failure",
              "Verify that the DAG's start_date and catchup settings produce the expected schedule",
              "Review DAG run logs for any skipped or failed tasks",
            ],
            codeExample: "# Check DAG structure in Airflow\nairflow tasks list dag_id --tree\n\n# Verify dependencies\nairflow tasks list dag_id --verbose\n\n# Check for all_done trigger rules (can mask failures)\n# Wrong: allows execution even if upstream failed\n# task_d = PythonOperator(task_id='task_d', trigger_rule='all_done', ...)\n# Right: requires all upstream to succeed\n# task_d = PythonOperator(task_id='task_d', trigger_rule='all_success', ...)",
            preventionTips: [
              "Review DAG code carefully before deployment",
              "Use CI/CD to validate DAG structure",
              "Set up DAG-level SLA alerts",
              "Monitor task duration trends to detect slowdowns before they cause ordering issues",
            ],
          },
        },
      ],
    },
  },
]
