import type { WorkflowPreset } from "@/shared/types/content"

export const workflowPresets: WorkflowPreset[] = [
  {
    id: "csv-to-db",
    name: "CSV to Database",
    description: "Simple file ingestion: read CSV files, validate, and load into a database table.",
    difficulty: "beginner",
    category: "batch",
    tags: ["CSV", "file", "ingest"],
    nodes: [
      { id: "source-1", type: "source", label: "CSV Files", position: { x: 50, y: 200 }, config: { path: "/data/input/*.csv", format: "CSV" } },
      { id: "transform-1", type: "transform", label: "Validate & Clean", position: { x: 300, y: 200 }, config: { rules: ["type_check", "null_check", "date_format"] } },
      { id: "load-1", type: "load", label: "PostgreSQL", position: { x: 550, y: 200 }, config: { table: "staging.orders", mode: "append" } },
    ],
    edges: [
      { id: "e-source-transform", source: "source-1", target: "transform-1", animated: true, label: "CSV rows" },
      { id: "e-transform-load", source: "transform-1", target: "load-1", animated: true, label: "Cleaned data" },
    ],
  },
  {
    id: "daily-sales-agg",
    name: "Daily Sales Aggregation",
    description: "Batch pipeline that aggregates daily sales from transaction data into summary tables.",
    difficulty: "beginner",
    category: "batch",
    tags: ["aggregation", "sales", "daily"],
    nodes: [
      { id: "source-1", type: "source", label: "Transactions DB", position: { x: 50, y: 150 }, config: { table: "transactions", filter: "date = yesterday" } },
      { id: "transform-1", type: "transform", label: "Join Products", position: { x: 280, y: 100 }, config: { join: "product_id" } },
      { id: "transform-2", type: "transform", label: "Aggregate Sales", position: { x: 280, y: 250 }, config: { group_by: ["product_id", "date"], agg: "SUM(amount)" } },
      { id: "load-1", type: "load", label: "Sales Summary", position: { x: 530, y: 150 }, config: { table: "daily_sales_summary", mode: "upsert" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "Raw transactions" },
      { id: "e2", source: "source-1", target: "transform-2", animated: true, label: "Raw transactions" },
      { id: "e3", source: "transform-1", target: "load-1", animated: true, label: "Enriched data" },
      { id: "e4", source: "transform-2", target: "load-1", animated: true, label: "Aggregated" },
    ],
  },
  {
    id: "incremental-load",
    name: "Incremental Load with CDC",
    description: "Change Data Capture pattern using timestamps to load only changed records.",
    difficulty: "intermediate",
    category: "batch",
    tags: ["CDC", "incremental", "watermark"],
    nodes: [
      { id: "source-1", type: "source", label: "Source DB", position: { x: 50, y: 200 }, config: { table: "orders", watermark_col: "updated_at" } },
      { id: "transform-1", type: "transform", label: "CDC Filter", position: { x: 280, y: 200 }, config: { watermark: "last_run", filter: "updated_at > watermark" } },
      { id: "transform-2", type: "transform", label: "Type Conversion", position: { x: 280, y: 350 }, config: { mapping: "source_to_target_types" } },
      { id: "load-1", type: "load", label: "Data Warehouse", position: { x: 530, y: 200 }, config: { table: "dw.orders", mode: "upsert" } },
      { id: "error-1", type: "errorHandler", label: "Error Queue", position: { x: 530, y: 350 }, config: { table: "error_log" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "All records" },
      { id: "e2", source: "transform-1", target: "transform-2", animated: true, label: "Changed records" },
      { id: "e3", source: "transform-1", target: "error-1", label: "Invalid records" },
      { id: "e4", source: "transform-2", target: "load-1", animated: true, label: "Converted data" },
    ],
  },
  {
    id: "scd-type2",
    name: "Slowly Changing Dimension (Type 2)",
    description: "Track historical changes to dimension attributes using SCD Type 2 with effective dates.",
    difficulty: "intermediate",
    category: "data-warehouse",
    tags: ["SCD", "dimension", "history"],
    nodes: [
      { id: "source-1", type: "source", label: "Source System", position: { x: 50, y: 200 }, config: { table: "customers", type: "OLTP" } },
      { id: "transform-1", type: "transform", label: "Detect Changes", position: { x: 280, y: 100 }, config: { algorithm: "hash_compare" } },
      { id: "transform-2", type: "transform", label: "SCD Type 2 Logic", position: { x: 280, y: 300 }, config: { method: "expire_old_insert_new" } },
      { id: "load-1", type: "load", label: "Dim Customers", position: { x: 530, y: 100 }, config: { table: "dim_customers", mode: "upsert" } },
      { id: "load-2", type: "load", label: "Dim History", position: { x: 530, y: 300 }, config: { table: "dim_customers_history", mode: "append" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "Current data" },
      { id: "e2", source: "transform-1", target: "transform-2", animated: true, label: "Changed records" },
      { id: "e3", source: "transform-1", target: "load-1", animated: true, label: "Unchanged" },
      { id: "e4", source: "transform-2", target: "load-2", animated: true, label: "Historical rows" },
    ],
  },
  {
    id: "real-time-stream",
    name: "Real-Time Stream Processing",
    description: "Stream processing pipeline ingesting events from Kafka, enriching, and loading to the warehouse.",
    difficulty: "advanced",
    category: "streaming",
    tags: ["Kafka", "streaming", "real-time"],
    nodes: [
      { id: "source-1", type: "source", label: "Kafka Topic", position: { x: 50, y: 150 }, config: { topic: "events.user_actions", consumer_group: "etl-group" } },
      { id: "transform-1", type: "transform", label: "Parse & Validate", position: { x: 280, y: 50 }, config: { schema: "avro", validation: "strict" } },
      { id: "transform-2", type: "transform", label: "Enrich with Lookup", position: { x: 280, y: 200 }, config: { lookup: "user_profile", cache_ttl: 300 } },
      { id: "transform-3", type: "transform", label: "Aggregate Window", position: { x: 280, y: 350 }, config: { window: "tumbling_5min" } },
      { id: "load-1", type: "load", label: "Clickhouse", position: { x: 530, y: 100 }, config: { table: "events_raw", batch_size: 1000 } },
      { id: "load-2", type: "load", label: "Redis Cache", position: { x: 530, y: 250 }, config: { key_pattern: "user:{id}:last_action" } },
      { id: "load-3", type: "load", label: "Real-Time Dashboard", position: { x: 530, y: 400 }, config: { type: "websocket" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "Raw events" },
      { id: "e2", source: "transform-1", target: "transform-2", animated: true, label: "Valid events" },
      { id: "e3", source: "transform-1", target: "transform-3", animated: true, label: "Valid events" },
      { id: "e4", source: "transform-2", target: "load-1", animated: true, label: "Enriched data" },
      { id: "e5", source: "transform-2", target: "load-2", animated: true, label: "Cache update" },
      { id: "e6", source: "transform-3", target: "load-3", animated: true, label: "Aggregated metrics" },
    ],
  },
  {
    id: "data-lake-ingest",
    name: "Data Lake Ingestion",
    description: "Raw data ingestion into a data lake with partitioning and Parquet format conversion.",
    difficulty: "intermediate",
    category: "data-lake",
    tags: ["data lake", "Parquet", "partitioning"],
    nodes: [
      { id: "source-1", type: "source", label: "API Gateway", position: { x: 50, y: 150 }, config: { method: "REST", endpoint: "/api/v2/events" } },
      { id: "source-2", type: "source", label: "Database Dumps", position: { x: 50, y: 300 }, config: { type: "pg_dump", schedule: "daily" } },
      { id: "transform-1", type: "transform", label: "Convert to Parquet", position: { x: 280, y: 150 }, config: { compression: "snappy" } },
      { id: "transform-2", type: "transform", label: "Partition by Date", position: { x: 280, y: 300 }, config: { partition_cols: ["year", "month", "day"] } },
      { id: "load-1", type: "load", label: "S3 / ADLS", position: { x: 530, y: 200 }, config: { path: "s3://data-lake/raw/", format: "parquet" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "JSON events" },
      { id: "e2", source: "source-2", target: "transform-2", animated: true, label: "SQL dumps" },
      { id: "e3", source: "transform-1", target: "load-1", animated: true, label: "Parquet files" },
      { id: "e4", source: "transform-2", target: "load-1", animated: true, label: "Partitioned data" },
    ],
  },
  {
    id: "multi-source-merge",
    name: "Multi-Source Merge",
    description: "Merge data from CRM, ERP, and web analytics into a unified customer view.",
    difficulty: "advanced",
    category: "data-warehouse",
    tags: ["merge", "CRM", "ERP", "360-view"],
    nodes: [
      { id: "source-1", type: "source", label: "CRM System", position: { x: 50, y: 80 }, config: { type: "Salesforce API" } },
      { id: "source-2", type: "source", label: "ERP System", position: { x: 50, y: 220 }, config: { type: "SAP", connector: "JDBC" } },
      { id: "source-3", type: "source", label: "Web Analytics", position: { x: 50, y: 360 }, config: { type: "Google Analytics 4" } },
      { id: "transform-1", type: "transform", label: "Normalize Schema", position: { x: 280, y: 80 }, config: { mapping: "crm_to_unified" } },
      { id: "transform-2", type: "transform", label: "Normalize Schema", position: { x: 280, y: 220 }, config: { mapping: "erp_to_unified" } },
      { id: "transform-3", type: "transform", label: "Normalize Schema", position: { x: 280, y: 360 }, config: { mapping: "web_to_unified" } },
      { id: "transform-merge", type: "transform", label: "Merge & Dedup", position: { x: 480, y: 220 }, config: { match_key: "customer_email", survivorship: "last_updated" } },
      { id: "load-1", type: "load", label: "Unified Customer 360", position: { x: 680, y: 220 }, config: { table: "customer_360", mode: "merge" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "Contacts" },
      { id: "e2", source: "source-2", target: "transform-2", animated: true, label: "Orders" },
      { id: "e3", source: "source-3", target: "transform-3", animated: true, label: "Events" },
      { id: "e4", source: "transform-1", target: "transform-merge", animated: true, label: "Normalized CRM" },
      { id: "e5", source: "transform-2", target: "transform-merge", animated: true, label: "Normalized ERP" },
      { id: "e6", source: "transform-3", target: "transform-merge", animated: true, label: "Normalized Web" },
      { id: "e7", source: "transform-merge", target: "load-1", animated: true, label: "Unified records" },
    ],
  },
  {
    id: "data-quality-pipeline",
    name: "Data Quality Pipeline",
    description: "Validate and cleanse incoming data with quality checks, quarantine, and dedup.",
    difficulty: "intermediate",
    category: "batch",
    tags: ["data quality", "validation", "cleansing"],
    nodes: [
      { id: "source-1", type: "source", label: "Raw Data", position: { x: 50, y: 200 }, config: { table: "raw_orders" } },
      { id: "transform-1", type: "transform", label: "Schema Validation", position: { x: 250, y: 80 }, config: { rules: ["column_count", "type_check", "not_null"] } },
      { id: "transform-2", type: "transform", label: "Data Quality Checks", position: { x: 250, y: 320 }, config: { rules: ["unique_key", "referential_integrity", "range_check"] } },
      { id: "error-1", type: "errorHandler", label: "Quarantine", position: { x: 480, y: 80 }, config: { table: "quarantine_log", action: "flag_and_reject" } },
      { id: "transform-3", type: "transform", label: "Dedup & Cleanse", position: { x: 480, y: 320 }, config: { dedup_key: "order_id", null_handling: "coalesce" } },
      { id: "load-1", type: "load", label: "Clean Data Mart", position: { x: 680, y: 200 }, config: { table: "clean_orders", mode: "overwrite" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "All rows" },
      { id: "e2", source: "source-1", target: "transform-2", animated: true, label: "All rows" },
      { id: "e3", source: "transform-1", target: "error-1", label: "Schema violations" },
      { id: "e4", source: "transform-2", target: "error-1", label: "Quality failures" },
      { id: "e5", source: "transform-1", target: "transform-3", animated: true, label: "Valid schema" },
      { id: "e6", source: "transform-2", target: "transform-3", animated: true, label: "Passed checks" },
      { id: "e7", source: "transform-3", target: "load-1", animated: true, label: "Clean records" },
    ],
  },
  {
    id: "star-schema-build",
    name: "Star Schema Build",
    description: "Build a star schema data model with fact and dimension tables from normalized source data.",
    difficulty: "advanced",
    category: "data-warehouse",
    tags: ["star schema", "dimensional", "fact", "dimension"],
    nodes: [
      { id: "source-1", type: "source", label: "Normalized DB", position: { x: 50, y: 200 }, config: { type: "PostgreSQL", schema: "public" } },
      { id: "transform-1", type: "transform", label: "Build Date Dim", position: { x: 280, y: 50 }, config: { granularity: "day", range: "2020-2030" } },
      { id: "transform-2", type: "transform", label: "Build Product Dim", position: { x: 280, y: 175 }, config: { scd: "type1", source_table: "products" } },
      { id: "transform-3", type: "transform", label: "Build Customer Dim", position: { x: 280, y: 300 }, config: { scd: "type2", source_table: "customers" } },
      { id: "transform-4", type: "transform", label: "Build Fact Table", position: { x: 280, y: 425 }, config: { grain: "order_line", measures: ["quantity", "total"] } },
      { id: "load-1", type: "load", label: "dim_date", position: { x: 530, y: 50 }, config: { table: "dim_date", mode: "upsert" } },
      { id: "load-2", type: "load", label: "dim_product", position: { x: 530, y: 175 }, config: { table: "dim_product", mode: "upsert" } },
      { id: "load-3", type: "load", label: "dim_customer", position: { x: 530, y: 300 }, config: { table: "dim_customer", mode: "scd2" } },
      { id: "load-4", type: "load", label: "fact_sales", position: { x: 530, y: 425 }, config: { table: "fact_sales", mode: "append" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "Schema metadata" },
      { id: "e2", source: "source-1", target: "transform-2", animated: true, label: "Products" },
      { id: "e3", source: "source-1", target: "transform-3", animated: true, label: "Customers" },
      { id: "e4", source: "source-1", target: "transform-4", animated: true, label: "Orders + line items" },
      { id: "e5", source: "transform-1", target: "load-1", animated: true, label: "Date rows" },
      { id: "e6", source: "transform-2", target: "load-2", animated: true, label: "Product rows" },
      { id: "e7", source: "transform-3", target: "load-3", animated: true, label: "Customer rows" },
      { id: "e8", source: "transform-4", target: "load-4", animated: true, label: "Fact rows" },
    ],
  },
  {
    id: "full-refresh",
    name: "Full Refresh Load",
    description: "Simple truncate-and-reload pattern for small reference tables or daily full refreshes.",
    difficulty: "beginner",
    category: "batch",
    tags: ["full refresh", "truncate", "reload"],
    nodes: [
      { id: "source-1", type: "source", label: "Source Table", position: { x: 50, y: 200 }, config: { table: "reference_data", type: "PostgreSQL" } },
      { id: "transform-1", type: "transform", label: "Truncate Target", position: { x: 280, y: 120 }, config: { table: "target.ref_data", action: "DELETE" } },
      { id: "transform-2", type: "transform", label: "Format & Map", position: { x: 280, y: 300 }, config: { mapping: "direct", transformations: [] } },
      { id: "load-1", type: "load", label: "Target Table", position: { x: 530, y: 200 }, config: { table: "target.ref_data", mode: "insert" } },
    ],
    edges: [
      { id: "e1", source: "source-1", target: "transform-1", animated: true, label: "Trigger" },
      { id: "e2", source: "source-1", target: "transform-2", animated: true, label: "All rows" },
      { id: "e3", source: "transform-1", target: "load-1", animated: true, label: "Truncate done" },
      { id: "e4", source: "transform-2", target: "load-1", animated: true, label: "Mapped rows" },
    ],
  },
]
